import pandas as pd
from sql_engine import connect
import json

dic1 = {
    "sourceTradeNo": "网店订单号",
    "tradeFrom": "贸易",
    "chargeCurrency": "币种",
    "shopId": "店铺id",
    "unit": "单位",
    "customerAccount": "客户账号",
    "tradeNo": "订单编号",
    "shopName": "销售渠道",
    "brandName": "品牌",
    "goodsNo": "货品编号",
    "goodsName": "货品名称",
    "specName": "规格",
    "sellCount": "数量",
    "sellPrice": "单价",
    "customerName": "客户名称",
    "logisticName": "物流公司",
    "mainPostid": "物流单号",
    "warehouseName": "发货仓库",
    "receiverName": "收货人",
    "address": "地址",
    "barcode": "货品条码",
    "discountFee": "优惠",
    "discountRate": "折扣",
    "sellTotal": "金额",
    "cost": "货品成本",
    "afterShareUnitFee": "分摊后单价",
    "shareFavourableFee": "分摊金额",
    "afterShareFee": "分摊后金额",
    "otherShareFavourableFee": "费用分摊",
    "grossProfit": "毛利",
    "grossProfitRate": "毛利率(%)",
    "unGrossProfit": "未税毛利",
    "unGrossProfitRate": "未税毛利率(%)",
    "tradeTypeExplain": "订单类型",
    "tradeFromExplain": "订单来源",
    "tradeStatusExplain": "订单状态",
    "sysFlagIds": "订单标记",
    "cateName": "货品类别",
    "untaxedUnitFee": "未税单价",
    "untaxedFee": "未税金额",
    "localAfterShareFee": "分摊后金额（本币）",
    "packageWeight": "包裹重量",
    "customerCode": "客户编号",
    "taxFee": "税额",
    "taxRate": "税率",
    "logisticTypeExplain": "配送方式",
    "seller": "业务员",
    "mobile": "手机",
    "phone": "电话",
    "tradeTime": "下单时间",
    "gmtCreate": "建单时间",
    "payTime": "付款时间",
    "auditTime": "审核时间",
    "consignTime": "发货时间",
    "customerPrice": "分销终端单价",
    "customerTotal": "分销终端金额",
    "goodsMemo": "货品备注",
    "ownerName": "货主",
    "billCheckTypeExplain": "对账状态",
    "estimateWeight": "预估重量(g)",
    "postFee": "预估邮资",
    "goodsReceivablePostage": "应收邮资",
    "sellerMemo": "客服备注",
    "buyerMemo": "客户备注",
    "companyName": "公司",
    "departName": "部门",
    "customerGradeName": "会员等级",
    "chargeTypeExplain": "结算方式",
    "accountName": "收款账户",
    "payNo": "支付单号",
    "customerTypeName": "客户分类",
    "endCustomerAccount": "终端客户账号",
    "terminalSalesNo": "终端销售单号",
    "agentTradeNo": "分销销售单号",
    "country": "国家",
    "state": "省",
    "city": "市",
    "district": "区（县）",
    "platGoodsId": "商品链接Id",
    "tradeGoodsNo": "网店规格编码",
    "tradeGoodsName": "交易名称",
    "tradeGoodsSpec": "交易规格",
    "tradeGoodsUnit": "交易单位",
    "appraisePrice": "考核价",
    "appraiseCost": "考核成本",
    "appraiseGrossProfit": "考核成本",
    "customerTradeNo": "终端网店单号",
    "customerSubtradeNo": "终端网店子订单号",
    "sourceSubtradeNo": "网店子订单号",
    "goodsAlias": "货品别名",
    "goodsEnName": "货品英文名称",
    "supplierItemNo": "供应商货号",
    "serialNo": "唯一码",
    "settleStatusExplain": "结算状态",
    "batchNo": "货品批次",
    # "baseGoods.skuNo": "货品规格编号",
    # "baseGoods.goodsField1": "货品-销售类型",
    # "baseGoods.goodsField2": "货品-渠道归属",
    # "baseGoods.colorName": "颜色",
    # "baseGoods.sizeName": "尺寸",
    # "baseGoods.materialName": "成分",
    "colorName": "颜色",
    "sizeName": "尺寸",
    "materialName": "成分",
    "skuNo": "货品规格编号",
    "goodsField1": "货品-销售类型",
    "goodsField2": "货品-渠道归属",
    "minPrice": "价格-最低售价",
    "price3": "价格-会员价",
    "price2": "价格-批发价",
    "price1": "价格-零售价"}

dic2 = {
    "customerAccount":'客户账号',
    "exchangeNo":'退换补发单号',
    "shopName":'销售渠道',
    "reasonDesc":'退换原因',
    "goodsNo":'货品编号',
    "goodsName":'货品名称',
    "specName":'规格',
    "unit":'单位',
    "price":'销售单价',
    "sendCount":'发货数量',
    "sendDiscounts":'发货优惠',
    "sendFee":'发货金额',
    "shareFavourableFee":'分摊金额',
    "shareFavourableTotalFee":'分摊后应退合计',
    "cost":'货品成本',
    "grossProfit":'毛利',
    "grossProfitRate":'毛利率(%)',
    "postFee":'预估邮资',
    "responsiblePersonDesc":'责任人',
    "exchangeStatus":'处理状态',
    "barcode":'货品条码',
    "flagIds":'退换单标记',
    "sourceExplain":'单据来源',
    "gmtCreate":'登记时间',
    "auditTime":'审核时间',
    "settlementDate":'结算时间',
    "deliveryPerson":'',
    "registrant":'',
    "auditor":'',
    "sourceTradeNo":'网店订单号',
    "targetNo":'订单编号(售后发货)',
    "sourceExchangeNo":'网店售后单号',
    "tradeNo":'订单编号(原)',
    "brandName":'品牌',
    "cateName":'分类',
    "remark":'货品备注',
    "customerName":'',
    "mobile":'',
    "applyTime":'',
    "sourcePayTime":'',
    "consignTime":'',
    "completeTime":'',
    "sourceWarehouseName":'发货仓库(原)',
    "appendMemo":'',
    "platGoodsId":'',
    "problemDesc":'',
    "customerRemark":'',
    "serviceRemark":'',
    "goodsField1":'',
    "goodsField2":''}
            
dic3 = {
    "customerAccount":'客户账号',
    "exchangeNo":'退换补发单号',
    "shopName":'销售渠道',
    "reasonDesc":'退换原因',
    "goodsNo":'货品编号',
    "goodsName":'货品名称',
    "specName":'规格',
    "unit":'单位',
    "price":'销售单价',
    "returnCount":'退货数量',
    "deliveryCount":'实退数量',
    "returnDiscounts":'退货优惠',
    "returnFee":'退货金额',
    "cost":'货品成本',
    "shareFavourableFee":'分摊金额',
    "shareFavourableTotalFee":'分摊后应退合计',
    "grossProfit":'毛利',
    "grossProfitRate":'毛利率(%)',
    "responsiblePersonDesc":'责任人',
    "exchangeStatus":'处理状态',
    "barcode":'货品条码',
    "deliveryPerson":'',
    "registrant":'',
    "auditor":'',
    "mobile":'手机',
    "sourceTradeNo":'网店订单号',
    "targetNo":'订单编号(售后退货)',
    "tradeNo":'订单编号(原)',
    "sourceExchangeNo":'网店售后单号',
    "brandName":'品牌',
    "cateName":'分类',
    "remark":'货品备注',
    "customerName":'客户名称',
    "sourceExplain":'单据来源',
    "flagIds":'退换单标记',
    "logisticName":'物流公司(退)',
    "mainPostid":'物流单号(退)',
    "sourceMainPostid":'物流单号(原)',
    "gmtCreate":'登记时间',
    "applyTime":'申请时间',
    "auditTime":'审核时间',
    "settlementDate":'结算时间',
    "deliveryTime":'收货时间',
    "sourcePayTime":'',
    "consignTime":'',
    "completeTime":'完成时间',
    "warehouseName":'收货仓库(退)',
    "sourceWarehouseName":'发货仓库(原)',
    "sourceLogisticName":'物流公司(原)',
    "picker":'',
    "packer":'',
    "boxuper":'',
    "allocator":'',
    "appendMemo":'',
    "platGoodsId":'',
    "deliveryCompleteRemark":'',
    "problemDesc":'',
    "customerRemark":'',
    "serviceRemark":'',
    "goodsField1":'',
    "goodsField2":''}
             
dic6 = {
   "warehouseName":'仓库',
   "goodsNo":'货品编号',
   "goodsName":'货品名称',
   "skuName":'规格',
   "unitName":'单位',
   "skuBarcode":'条码',
   "brandName":'品牌',
   "cateName":'分类',
   "isCertified":'正品',
   "quantity":'库存量'}

dic8 = {  
    "vendCustomerName":'往来单位',
    "billNo":'关联单号',
    "sourceBillNo":'来源单号',
    "deliveryNo":'收发货单号',
    "warehouseName":'仓库',
    "trDate":'出入库时间',
    "systemTrDate":'系统出入库时间',
    "inouttypeName":'出入库类型',
    "goodsdocNo":'单据编号',
    "goodsNo":'货品编号',
    "goodsName":'货品名称',
    "skuName":'规格',
    "skuBarcode":'条码',
    "channelName":'销售渠道',
    "retailPrice":'固定成本价',
    "retailAmtIn":'固定入库成本',
    "retailAmtOut":'固定出库成本',
    "unitName":'单位',
    "isCertified":'正品',
    "inCuPrice":'入库单价',
    "inQuantity":'入库数量',
    "inCuValue":'入库金额',
    "outCuPrice":'出库单价',
    "outQuantity":'出库数量',
    "outCuValue":'出库金额',
    "companyName":'公司',
    "userName":'操作员',
    "memo":'收发货备注',
    "applyMemo":'申请单备注',
    "rowRemark":'货品备注',
    "comment":'备注',
    "inOutReason":'出入库原因',
    "settFeeAmount":'入库费用',
    "estCost":'入库含税金额',
    "estTax":'入库税额',
    "applyCompanyName":'申请公司',
    "applyDepartName":'申请部门',
    "applyUserName":'',
    "cateName":'分类',
    "brandName":'品牌',
    "goodsAlias":'别名',
    "goodsNameEn":'英文名称',
    "outBillNo":'外部单号',
    "batchNo":'批次',
    "serialNo":'唯一码',
    "goodsField1":'销售类型',
    "goodsField2":'渠道归属'       
}

# dic11 = {
#   "tradeOrder.orderNo":'',
#   "tradeOrder.tradeStatus":'',
#   "tradeOrder.payment":'',
#   "tradeOrderInvoice.invoiceStatus":'',
#   "tradeOrder.warehouseId":'',
#   "tradeOrder.flagIds":'',
#   "tradeOrder.tradeCount":'',
#   "tradeOrder.consignTime":'',
#   "tradeOrder.tradeTime":'',
#   "tradeOrder.confirmTime":'',
#   "tradeOrder.tradeType":'',
#   "tradeOrder.settleStatus":'',
#   "tradeOrderCustomer.customerName":'',
#   "tradeOrderCustomer.email":'',
#   "tradeOrder.lastShipTime":'',
#   "tradeOrderCustomer.customerId":'',
#   "sourceTradeNo":'',
#   "tradeOrder.tradeFrom":'',
#   "tradeOrder.shopId":'',
#   "tradeOrder.tradeNo":'',
#   "tradeOrder.tradeStatusExplain":'',
#   "tradeOrder.shopName":'',
#   "tradeOrder.tradeFromExplain":'',
#   "tradeOrder.handleTime":'',
#   "tradeOrder.payTime":'',
#   "tradeOrder.warehouseName":'',
#   "tradeOrder.logisticName":'',
#   "tradeOrder.mainPostid":'',
#   "tradeOrder.tradeTypeExplain":'',
#   "tradeOrder.totalFee":'',
#   "tradeOrder.seller":'',
#   "tradeOrder.goodslist":'',
#   "tradeOrderCustomer.customerAccount":'',
#   "tradeOrderReceiver.receiverName":'',
#   "tradeOrderReceiver.mobile":'',
#   "tradeOrderReceiver.phone":'',
#   "tradeOrderReceiver.address":'',
#   "mergeRemarks":'',
#   "tradeOrder.logisticStatusExplain":'',
#   "tradeOrder.settleStatusExplain":'',
#   "tradeOrder.distributionStation":'',
#   "tradeOrder.gmtCreate":'',
#   "tradeOrder.arriveTime":'',
#   "tradeOrder.payStatusExplain":'',
#   "tradeOrder.payDueDate":'',
#   "extraLogisticNo":'',
#   "platLogisticName":'',
#   "platLogisticCode":'',
#   "platWarehouseCode":'',
#   "tradeOrderAgentExtra.agentTradeNo":'',
#   "tradeOrderAgentExtra.terminalSalesNo":'',
#   "targetTradeAfterNo":'',
#   "sourceTradeAfterNo":'',
#   "tradeOrder.auditTime":'',
#   "tradeOrder.reviewTime":'',
#   "tradeOrder.notifyPickTime":'',
#   "tradeOrder.logisticTypeExplain":'',
#   "tradeOrder.taxFee":'',
#   "tradeOrder.discountFee":'',
#   "localPayment":'',
#   "tradeOrder.receivedPostFee":'',
#   "tradeOrder.postFee":'',
#   "tradeOrder.warehouseFee":'',
#   "tradeOrder.otherFee":'',
#   "tradeOrder.couponFee":'',
#   "tradeOrder.grossProfit":'',
#   "tradeOrderFin.billDate":'',
#   "tradeOrderFin.billCheckTypeExplain":'',
#   "tradeOrderFin.checkTotal":'',
#   "tradeOrder.accountName":'',
#   "tradeOrder.chargeTypeExplain":'',
#   "tradeOrder.chargeCurrency":'',
#   "tradeOrder.payNo":'',
#   "tradeOrder.buyerMemo":'',
#   "tradeOrder.sellerMemo":'',
#   "tradeOrder.merchandiser":'',
#   "tradeOrder.register":'',
#   "tradeOrder.auditor":'',
#   "tradeOrder.reviewer":'',
#   "tradeOrder.estimateWeight":'',
#   "tradeOrder.estimateVolume":'',
#   "tradeOrder.packageWeight":'',
#   "tradeOrder.goodsTypeCount":'',
#   "tradeOrder.stockoutNo":'',
#   "tradeOrderAgentExtra.supplierName":'',
#   "tradeOrderInvoice.invoiceTypeExplain":'',
#   "tradeOrderInvoice.payerName":'',
#   "tradeOrderInvoice.payerRegno":'',
#   "tradeOrderInvoice.invoiceStatusExplain":'',
#   "tradeOrderInvoice.invoiceAmount":'',
#   "tradeOrderInvoice.invoicedAmount":'',
#   "tradeOrderInvoice.invoiceNo":'',
#   "tradeOrderPre.preTypedetail":'',
#   "tradeOrderPre.firstPaytime":'',
#   "tradeOrderPre.finalPaytime":'',
#   "tradeOrderPre.activationTime":'',
#   "tradeOrderReceiver.identityCardTypeExplain":'',
#   "tradeOrderReceiver.identityCardNo":'',
#   "tradeOrderReceiver.identityCardName":'',
#   "tradeOrderReceiver.country":'',
#   "tradeOrderReceiver.state":'',
#   "tradeOrderReceiver.city":'',
#   "tradeOrderReceiver.district":'',
#   "tradeOrderReceiver.town":'',
#   "tradeOrderCustomer.endCustomerAccount":'',
#   "goodsImgInfo":'',
#   "onlineImgInfo":'',
#   "tradeOrder.appendMemo":'',
#   "tradeCost":'',
#   "grossProfitRate":'',
#   "sourceSubtradeNo":'',
#   "tradeOrder.customerPayment":'',
#   "tradeOrder.customerDiscountFee":'',
#   "tradeOrder.customerPostFee":'',
#   "tradeOrder.customerTotalFee":'',
#   "tradeOrder.uploadMarketExplain":'',
#   "tradeOrder.expectReachTime":'',
#   "tradeOrder.distributeLimitationExplain":'',
#   "tradeOrder.customerPayNo":'',
#   "tradeOrder.customerTaxFee":'',
#   "tradeOrder.cancelReason":'',
#   "tradeOrder.insuredValue":'',
#   "tradeOrderAgentExtra.agentShopName":'',
#   "tradeOrder.pickupTime":'',
#   "platName":'',
#   "realFee":'',
#   "tradeOrder.sourceTradeType":'',
#   "tradeOrder.salesName":'',
#   "tradeOrder.completeTime":''}
           
    


def rename_format(df, num):
    if num == 1 or num == 9 or num == 10:
        df['colorName'] = df.baseGoods.apply(lambda x :x['colorName'] if x != None else None)
        df['sizeName'] = df.baseGoods.apply(lambda x :x['sizeName'] if x != None else None)
        df['materialName'] = df.baseGoods.apply(lambda x :x['materialName'] if x != None else None)
        df['skuNo'] = df.baseGoods.apply(lambda x :x['skuNo'] if x != None else None)
        df['goodsField1'] = df.baseGoods.apply(lambda x :x['goodsField1'] if x != None else None)
        df['goodsField2'] = df.baseGoods.apply(lambda x :x['goodsField2'] if x != None else None)
        df.rename(columns=dic1, inplace=True)
        df = df[['客户账号', '网店订单号', '订单编号', '销售渠道', '品牌', '货品编号', '货品名称', '规格', '数量', '单价', '优惠', '折扣', '金额', '货品成本', '分摊后单价', '分摊金额', '分摊后金额',
                 '费用分摊','毛利','毛利率(%)','未税毛利','未税毛利率(%)','货品条码','收货人','订单标记','客户名称','物流公司','物流单号','发货仓库',
                 '业务员',
                 '订单状态',
                 '货品备注',
                 '单位',
                 '未税单价',
                 '未税金额',
                 '分摊后金额（本币）',
                 '包裹重量',
                 '订单类型',
                 '订单来源',
                 '税额',
                 '税率',
                 '手机',
                 '电话',
                 '地址',
                 '下单时间',
                 '建单时间',
                 '付款时间',
                 '审核时间',
                 '发货时间',
                 '货主',
                 '对账状态',
                 '币种',
                 '收款账户',
                 '支付单号',
                 '终端客户账号',
                 '终端销售单号',
                 '分销销售单号',
                 '国家',
                 '省',
                 '市',
                 '区（县）',
                 '网店规格编码',
                 '交易规格',
                 '交易单位',
                 '货品-销售类型',
                 '货品-渠道归属',
                 '货品类别',
                 '交易名称',
                 '货品别名',
                 '结算状态',
                 '供应商货号',
                 '客服备注']]
    
    elif num ==2:
        df.rename(columns=dic2, inplace=True)
        df = df[['客户账号',
                    '退换补发单号',
                    '销售渠道',
                    '退换原因',
                    '货品编号',
                    '货品名称',
                    '规格',
                    '单位',
                    '销售单价',
                    '发货数量',
                    '发货优惠',
                    '发货金额',
                    '分摊金额',
                    '分摊后应退合计',
                    '货品成本',
                    '毛利',
                    '毛利率(%)',
                    '预估邮资',
                    '责任人',
                    '处理状态',
                    '货品条码',
                    '退换单标记',
                    '单据来源',
                    '登记时间',
                    '审核时间',
                    '结算时间',
                    '网店订单号',
                    '订单编号(售后发货)',
                    '网店售后单号',
                    '订单编号(原)',
                    '品牌',
                    '分类',
                    '发货仓库(原)',
                    '货品备注',]]
    
    elif num ==3:
        df.rename(columns=dic3, inplace=True)
        df = df[['客户账号',
                '退换补发单号',
                '销售渠道',
                '退换原因',
                '货品编号',
                '货品名称',
                '规格',
                '单位',
                '销售单价',
                '退货数量',
                '实退数量',
                '退货优惠',
                '退货金额',
                '货品成本',
                '分摊金额',
                '分摊后应退合计',
                '毛利',
                '毛利率(%)',
                '责任人',
                '处理状态',
                '货品条码',
                '手机',
                '网店订单号',
                '订单编号(售后退货)',
                '订单编号(原)',
                '网店售后单号',
                '品牌',
                '分类',
                '货品备注',
                '客户名称',
                '单据来源',
                '退换单标记',
                '物流公司(退)',
                '物流单号(退)',
                '登记时间',
                '审核时间',
                '结算时间',
                '收货时间',
                '收货仓库(退)',
                '发货仓库(原)',
                '物流公司(原)']]
      
    elif num ==6 or num ==7:
        df.rename(columns=dic6, inplace=True)                
        df = df[['仓库',
                '货品编号',
                '货品名称',
                '规格',
                '单位',
                '条码',
                '品牌',
                '分类',
                '正品',
                '库存量']]
      
    elif num==8:
        df.rename(columns=dic8,inplace=True)
        df = df[['往来单位',
                '关联单号',
                '来源单号',
                '仓库',
                '出入库时间',
                '系统出入库时间',
                '出入库类型',
                '单据编号',
                '货品编号',
                '货品名称',
                '规格',
                '条码',
                '销售渠道',
                '固定成本价',
                '固定入库成本',
                '固定出库成本',
                '单位',
                '正品',
                '入库单价',
                '入库数量',
                '入库金额',
                '出库单价',
                '出库数量',
                '出库金额',
                '公司',
                '操作员',
                '备注',
                '出入库原因',
                '入库费用',
                '入库含税金额',
                '申请公司',
                '申请部门',
                '分类',
                '品牌',
                '别名',
                '收发货单号']]   
    
    # elif num == 11:
    #     df['colorName'] = df.baseGoods.apply(lambda x :x['colorName'])
    #     df['sizeName'] = df.baseGoods.apply(lambda x :x['sizeName'])
    #     df['materialName'] = df.baseGoods.apply(lambda x :x['materialName'])
    #     df['skuNo'] = df.baseGoods.apply(lambda x :x['skuNo'])
    #     df['goodsField1'] = df.baseGoods.apply(lambda x :x['goodsField1'])
    #     df['goodsField2'] = df.baseGoods.apply(lambda x :x['goodsField2'])
    #     df.rename(columns=dic11,inplace=True)
    #     df = df[['标记',
    #             '订单编号',
    #             '订单状态',
    #             '结算状态',
    #             '销售渠道',
    #             '处理时间',
    #             '付款时间',
    #             '发货仓库',
    #             '物流公司',
    #             '物流单号',
    #             '网店订单号',
    #             '发货单号',
    #             '发货时间',
    #             '订单类型',
    #             '应收合计',
    #             '货品数量',
    #             '客户账号',
    #             '收货人',
    #             '手机',
    #             '电话',
    #             '地址',
    #             '物流状态',
    #             '省',
    #             '市',
    #             '区（县）',
    #             '物流公司（平台）',
    #             '物流编码（平台）',
    #             '应收邮资',
    #             '预估邮资',
    #             '终端应收邮资'      
    #     ]]
    
    return df












